kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: dockerconfigjson-github-com
stringData:
  .dockerconfigjson: >- 
    {
      "auths": {
        "ghcr.io":{
          "auth": "QmVuZVVYOmdocF9iRU5FNDZpTG4wS1Vaa1ViWVo2dGdEUmIwamdVdGU0YVBrV3Q="
        }
      }
    }

