kind: Service
apiVersion: v1
metadata:
  name: todo-frontend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      nodePort: 31001
  selector:
    app: todo-frontend
