kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: dockerconfigjson-github-com
  namespace: argocd	
stringData:
  .dockerconfigjson: >-
    {
      "auths": {
        "ghcr.io":{
          "auth": "QmVuZVVYOmdocF9jR0FRSkdickhlY3lZVEtWS0pCVk4wWWpRNFg2VkkzUFF3b3M="
        }
      }
    }

