apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-frontend
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/BeneUX/todo-frontend.git
    targetRevision: HEAD
    path: ./helm/templates

  destination:
    server: https://kubernetes.default.svc
    namespace: todo-frontend-argocd

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
